/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIConfigDialog.java
 *
 * Created on 24-lug-2010, 1.16.18
 */

package it.losko.hotel.view.gui;

import it.losko.hotel.model.conf.Config;
import it.losko.hotel.model.conf.ConfigConstants;
import it.losko.hotel.model.conf.InvalidParameterException;
import it.losko.hotel.model.info.Info;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author losko
 */
public class GUIConfigDialog extends javax.swing.JDialog {
	private static final long serialVersionUID = 1L;
	
	private final GUI gui;
	private final List<JSpinner> spinners;
	private final List<JTextField> textFields;
	private final List<JComboBox> comboBoxes;
	
	/** Creates new form GUIConfigDialog */
    public GUIConfigDialog(final GUI gui, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        this.gui = gui;
        spinners = new ArrayList<JSpinner>();
        textFields = new ArrayList<JTextField>();
        comboBoxes = new ArrayList<JComboBox>();
        
        initComponents();
        setLocationRelativeTo(parent);
        
        catalogueSpinnerComponents();
        catalogueTextFieldComponents();
        catalogueComboBoxComponents();
    }
    
    public GUI getGui() {
		return gui;
	}

	private void catalogueSpinnerComponents() {
    	spinners.add(numberOfLapsForecastingSpinner);
    	spinners.add(actionDelaySpinner);
    	spinners.add(turnDelaySpinner);
    	spinners.add(inputTimeoutSpinner);
    }
    
    private void catalogueTextFieldComponents() {
    	textFields.add(logsFolderTextField);
    	textFields.add(userInterfaceClassNameTextField);
    }

    private void catalogueComboBoxComponents() {
    	comboBoxes.add(actionsLogsLevelComboBox);
    	comboBoxes.add(listenersLogsLevelComboBox);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        okButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        numberOfLapsForecastingLabel = new javax.swing.JLabel();
        numberOfLapsForecastingSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        actionDelayLabel = new javax.swing.JLabel();
        actionDelaySpinner = new javax.swing.JSpinner();
        turnDelayLabel = new javax.swing.JLabel();
        turnDelaySpinner = new javax.swing.JSpinner();
        inputTimeoutLabel = new javax.swing.JLabel();
        inputTimeoutSpinner = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        logsFolderLabel = new javax.swing.JLabel();
        logsFolderTextField = new javax.swing.JTextField();
        actionsLogsLevelLabel = new javax.swing.JLabel();
        actionsLogsLevelComboBox = new javax.swing.JComboBox();
        listenersLogsLevelLabel = new javax.swing.JLabel();
        listenersLogsLevelComboBox = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        userInterfaceClassNameLabel = new javax.swing.JLabel();
        userInterfaceClassNameTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Info.getSingleton().getName() + " - Configuration");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        numberOfLapsForecastingLabel.setText("Number of laps forecasting:");

        numberOfLapsForecastingSpinner.setName(ConfigConstants.PARAM_NUMBER_OF_LAP_FORECASTING);
        numberOfLapsForecastingSpinner.setValue(Config.getSingleton().getParameterValueAsInteger(ConfigConstants.PARAM_NUMBER_OF_LAP_FORECASTING));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numberOfLapsForecastingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfLapsForecastingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfLapsForecastingLabel)
                    .addComponent(numberOfLapsForecastingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Artificial intelligence", jPanel1);

        actionDelayLabel.setText("Actions' delay:");

        actionDelaySpinner.setName(ConfigConstants.PARAM_ACTION_DELAY
        );
        actionDelaySpinner.setValue(Config.getSingleton().getParameterValueAsInteger(ConfigConstants.PARAM_ACTION_DELAY));

        turnDelayLabel.setText("Turn's delay:");

        turnDelaySpinner.setName(ConfigConstants.PARAM_TURN_DELAY);
        turnDelaySpinner.setValue(Config.getSingleton().getParameterValueAsInteger(ConfigConstants.PARAM_TURN_DELAY));

        inputTimeoutLabel.setText("Input's timeout:");

        inputTimeoutSpinner.setName(ConfigConstants.PARAM_INPUT_TIMEOUT);
        inputTimeoutSpinner.setValue(Config.getSingleton().getParameterValueAsInteger(ConfigConstants.PARAM_INPUT_TIMEOUT));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionDelayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(turnDelayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turnDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputTimeoutLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTimeoutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actionDelayLabel)
                    .addComponent(actionDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnDelayLabel)
                    .addComponent(turnDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTimeoutLabel)
                    .addComponent(inputTimeoutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Delays", jPanel2);

        logsFolderLabel.setText("Logs' folder:");

        logsFolderTextField.setText(Config.getSingleton().getParameterValueAsString(ConfigConstants.PARAM_LOG_FOLDER));
        logsFolderTextField.setName(ConfigConstants.PARAM_LOG_FOLDER);

        actionsLogsLevelLabel.setText("Actions' logs level:");

        actionsLogsLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OFF", "SEVERE", "WARNING", "INFO", "CONFIG", "FINE", "FINER", "FINEST", "ALL" }));
        actionsLogsLevelComboBox.setSelectedItem(Config.getSingleton().getParameterValueAsString(ConfigConstants.PARAM_ACTION_LOG_LEVEL));
        actionsLogsLevelComboBox.setName(ConfigConstants.PARAM_ACTION_LOG_LEVEL);

        listenersLogsLevelLabel.setText("Listeners' logs level:");

        listenersLogsLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OFF", "SEVERE", "WARNING", "INFO", "CONFIG", "FINE", "FINER", "FINEST", "ALL" }));
        listenersLogsLevelComboBox.setSelectedItem(Config.getSingleton().getParameterValueAsString(ConfigConstants.PARAM_LISTENER_LOG_LEVEL));
        listenersLogsLevelComboBox.setName(ConfigConstants.PARAM_LISTENER_LOG_LEVEL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(logsFolderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logsFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(actionsLogsLevelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionsLogsLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listenersLogsLevelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listenersLogsLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logsFolderLabel)
                    .addComponent(logsFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actionsLogsLevelLabel)
                    .addComponent(actionsLogsLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listenersLogsLevelLabel)
                    .addComponent(listenersLogsLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Logs", jPanel3);

        userInterfaceClassNameLabel.setText("User interface class' name:");

        userInterfaceClassNameTextField.setText(Config.getSingleton().getParameterValueAsString(ConfigConstants.PARAM_USER_INTERFACE_CLASS_NAME));
        userInterfaceClassNameTextField.setName(ConfigConstants.PARAM_USER_INTERFACE_CLASS_NAME);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userInterfaceClassNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInterfaceClassNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInterfaceClassNameLabel)
                    .addComponent(userInterfaceClassNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        tabbedPane.addTab("User interface", jPanel4);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset to defaults");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton))
                    .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton)
                    .addComponent(resetButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    	for(final JSpinner f : spinners) {
			try {
				Config.getSingleton().updateParameterValue(f.getName(), String.valueOf(f.getValue()));
			} catch (final InvalidParameterException e1) {
				// TODO Auto-generated catch block
				return;
			}
		}
    	
    	for(final JTextField f : textFields) {
			try {
				Config.getSingleton().updateParameterValue(f.getName(), f.getText());
			} catch (final InvalidParameterException e1) {
				// TODO Auto-generated catch block
				return;
			}
		}
    	
    	for(final JComboBox f : comboBoxes) {
			try {
				Config.getSingleton().updateParameterValue(f.getName(), (String) f.getSelectedItem());
			} catch (final InvalidParameterException e1) {
				System.out.println("test");
				// TODO Auto-generated catch block
				return;
			}
		}
    	
		Config.getSingleton().save();
		dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
    	for(final JSpinner f : spinners) {
    		f.setValue(Integer.valueOf(Config.getSingleton().getParameter(f.getName()).getDefaultValue()));
    	}

    	for(final JTextField f : textFields) {
    		f.setText(Config.getSingleton().getParameter(f.getName()).getDefaultValue());
    	}

    	for(final JComboBox f : comboBoxes) {
    		f.setSelectedItem(Config.getSingleton().getParameter(f.getName()).getDefaultValue());
    	}
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    	dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionDelayLabel;
    private javax.swing.JSpinner actionDelaySpinner;
    private javax.swing.JComboBox actionsLogsLevelComboBox;
    private javax.swing.JLabel actionsLogsLevelLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel inputTimeoutLabel;
    private javax.swing.JSpinner inputTimeoutSpinner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox listenersLogsLevelComboBox;
    private javax.swing.JLabel listenersLogsLevelLabel;
    private javax.swing.JLabel logsFolderLabel;
    private javax.swing.JTextField logsFolderTextField;
    private javax.swing.JLabel numberOfLapsForecastingLabel;
    private javax.swing.JSpinner numberOfLapsForecastingSpinner;
    private javax.swing.JButton okButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel turnDelayLabel;
    private javax.swing.JSpinner turnDelaySpinner;
    private javax.swing.JLabel userInterfaceClassNameLabel;
    private javax.swing.JTextField userInterfaceClassNameTextField;
    // End of variables declaration//GEN-END:variables

}
